version: '3.8'

services:
  powersync-api:
    image: journeyapps/powersync-service:latest
    command: ["start", "-r", "api"]
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=800
      - POWERSYNC_CONFIG_PATH=/config/powersync.yaml
    volumes:
      - ./config:/config
    networks:
      - powersync-net
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1024M
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:${PS_PORT}/probes/liveness').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"
        ]
      interval: 5s
      timeout: 1s
      retries: 15

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - powersync-api
    networks:
      - powersync-net
    restart: unless-stopped

networks:
  powersync-net:
    driver: bridge