version: '3.8'

services:
  powersync-sync:
    image: journeyapps/powersync-service:latest
    command: ["start", "-r", "sync"]
    container_name: powersync-sync
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024
      - PS_MONGO_URI=${PS_MONGO_URI}
      - PS_DATA_SOURCE_URI=${PS_DATA_SOURCE_URI}
      - PS_PORT=${PS_PORT}
      - PS_JWKS_URL=${PS_JWKS_URL}
    volumes:
      - ./config/powersync.yaml:/config/powersync.yaml:ro
      - ./config/sync_rules.yaml:/config/sync_rules.yaml:ro
    networks:
      - powersync-net
    restart: unless-stopped

  powersync-api:
    image: journeyapps/powersync-service:latest
    command: ["start", "-r", "api"]
    ports:
      - "8080-8099:80"
    environment:
      - NODE_OPTIONS=--max-old-space-size=800
      - PS_MONGO_URI=${PS_MONGO_URI}
      - PS_DATA_SOURCE_URI=${PS_DATA_SOURCE_URI}
      - PS_PORT=${PS_PORT}
      - PS_JWKS_URL=${PS_JWKS_URL}
    volumes:
      - ./config/powersync.yaml:/config/powersync.yaml:ro
      - ./config/sync_rules.yaml:/config/sync_rules.yaml:ro
    depends_on:
      - powersync-sync
    networks:
      - powersync-net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - powersync-api
    networks:
      - powersync-net
    restart: unless-stopped

networks:
  powersync-net:
    driver: bridge
