telemetry:
  disable_telemetry_sharing: true

replication:
  connections:
    - type: postgresql
      uri: !env PS_DATA_SOURCE_URI
      sslmode: verify-full

storage:
  type: postgresql
  uri: !env PS_STORAGE_POSTGRESQL_URI

port: !env PS_PORT

sync_rules:
  path: /config/sync_rules.yaml

client_auth:
  jwks:
    keys:
      - kty: 'oct'
        k: !env PS_JWKS_KEY
        alg: !env PS_JWKS_ALG
  audience: [!env PS_JWKS_AUDIENCE]

api:
  tokens:
    - !env PS_API_TOKEN

# migrations:
#   disable_auto_migration: false